eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: ${HOST_NAME}
      instance-id: ${spring.application.name}:${instanceId:${random.value}}

#server:
#  port: 0
spring:
  application:
    name: payment-service
